/**
 * The modules behind `@srljs/core` in an import map. Generated by `npm run importmap`
 * from the same door as `dist/srl-core.js`, so do not edit it. ADR-0124.
 */

export * from '@auth/guard.js';
export * from '@auth/session-fetch.js';
export * from '@auth/session-policy.js';
export * from '@auth/session.js';
export * from '@core/appearance/theme.js';
export { runningRelease, releaseChanged, watchRelease } from '@core/application/release.js';
export * from '@core/application/runtime.js';
export * from '@core/application/worker.js';
export * from '@core/diagnostics/report.js';
export { recordUpdates, isRecordingUpdates } from '@core/diagnostics/updates.js';
export { defineComponent, definitionOf, tagOf, resolveTag } from '@core/elements/component.js';
export * from '@core/elements/element-defaults.js';
export * from '@core/elements/mount.js';
export * from '@core/elements/outlet.js';
import '@core/elements/projection.js';
export * from '@core/elements/settled.js';
export * from '@core/elements/signal-element.js';
export { OWNER_ATTRIBUTE } from '@core/elements/style-scope.js';
import '@core/elements/stylesheet.js';
export * from '@core/forms/array.js';
export * from '@core/forms/field.js';
export * from '@core/forms/group.js';
export * from '@core/forms/settled.js';
export * from '@core/forms/validators.js';
export * from '@core/foundation/clock.js';
export { token, provide, inject } from '@core/foundation/inject.js';
export * from '@core/foundation/json.js';
export * from '@core/foundation/reactive.js';
export * from '@core/foundation/resource.js';
export * from '@core/http/client.js';
export * from '@core/localization/i18n.js';
export * from '@core/navigation/router.js';
export { configurePreferences, loadPreference, savePreference, removePreference, createMemoryStorage } from '@core/preferences/persistence.js';
export { admitManifest } from '@core/remotes/manifest-policy.js';
export * from '@core/remotes/mfe.js';
import '@core/template/dialect.js';
export { ExpressionError, parseExpression } from '@core/template/expression-parser.js';
export * from '@core/template/expression.js';
export { bypassSecurityTrustHtml, bypassSecurityTrustStyle, bypassSecurityTrustUrl, bypassSecurityTrustResourceUrl, attributeSinkFor, propertySinkFor } from '@core/template/security.js';
export { loadTemplate, prefetchTemplates, registerTemplateGroups, seedTemplates, attachTemplate, templateFor } from '@core/template/template.js';
export * from '@host/remote-host.js';
export * from '@host/runtime.js';
