/**
 * The source entry module behind a bundle's bare specifier, for the import map.
 *
 * A bundler resolves `@srljs/core` through `exports` to `dist/srl-core.js`. A browser
 * resolves it through the import map to the module written here, which re-exports the
 * same door from the files the deep `@core/` paths load. One spelling then works in both
 * shapes, and a page that mixes `@srljs/core` with `@core/...` still evaluates each
 * module once, so it keeps one element registry. ADR-0124.
 *
 * A bundle offers an entry when `srl.bundles.<name>.entry` names one. The component
 * bundle offers none, because importing a component registers it, and an entry would
 * register every component on every page.
 *
 *   node cli/package/entry.mjs            print every entry module
 *   node cli/package/entry.mjs --write    write them
 *
 * `npm run verify` fails when a written entry is stale.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { walk } from '../layout.mjs';
import { barrelSource, moduleDoor } from './door.mjs';
import { BUNDLES, PACKAGE, SPECIFIER_DIRS } from './interface.mjs';

/** @import { ModuleDoor } from './door.mjs' */
/** @import { PackageBundle } from './interface.mjs' */

/**
 * Test source, decided on the path relative to the package rather than the absolute
 * one. It is the same rule the project model follows, for the same reason, because a
 * checkout that happens to sit under a directory called `test` is not a suite.
 *
 * @param {string} path
 * @returns {boolean}
 */
export function isTestSource(path) {
  const inside = relative(PACKAGE, path);
  return inside.split(sep).includes('test') || inside.endsWith('.test.js');
}

/**
 * The modules one bundle is a barrel over, sorted so every barrel built from them is
 * stable byte for byte across machines.
 *
 * @param {PackageBundle} bundle
 * @returns {Promise<string[]>}
 */
export async function bundleMembers(bundle) {
  /** @type {string[]} */
  const files = [];
  for (const root of bundle.roots) files.push(...(await walk(root, /\.js$/u)));
  return [...new Set(files)]
    .filter((file) => !isTestSource(file))
    .filter((file) => !bundle.excluded.some((dir) => file.startsWith(dir + sep)))
    .filter((file) => file !== bundle.entry)
    .sort();
}

/**
 * What each member offers, read out of the member. `door.mjs` owns the rule, so the
 * dist barrel, its declaration and the source entry offer one set of names. ADR-0066.
 *
 * @param {string[]} members
 * @returns {Promise<Array<{ file: string, door: ModuleDoor }>>}
 */
export async function bundleDoors(members) {
  /** @type {Array<{ file: string, door: ModuleDoor }>} */
  const doors = [];
  for (const file of members) {
    doors.push({ file, door: moduleDoor(await readFile(file, 'utf8'), file) });
  }
  return doors;
}

/**
 * The library specifier a member file is imported under, such as `@core/http/client.js`.
 *
 * @param {string} file
 * @returns {string}
 */
function specifierFor(file) {
  for (const [prefix, dir] of Object.entries(SPECIFIER_DIRS)) {
    if (file.startsWith(dir + sep)) return `${prefix}${relative(dir, file).split(sep).join('/')}`;
  }
  throw new Error(`${file} is under no library prefix, so no specifier names it.`);
}

/**
 * The bundles that offer an entry module.
 *
 * @returns {Array<PackageBundle & { entry: string }>}
 */
export function entryBundles() {
  return /** @type {Array<PackageBundle & { entry: string }>} */ (
    BUNDLES.filter((bundle) => bundle.entry !== undefined)
  );
}

/**
 * One bundle's entry module, as the bytes on disk.
 *
 * @param {PackageBundle} bundle
 * @returns {Promise<string>}
 */
export async function entryText(bundle) {
  const doors = await bundleDoors(await bundleMembers(bundle));
  const barrel = barrelSource(doors.map(({ file, door }) => ({ file: specifierFor(file), door })));
  return (
    `/**\n` +
    ` * The modules behind \`${bundle.specifier}\` in an import map. Generated by \`npm run importmap\`\n` +
    ` * from the same door as \`${bundle.file}\`, so do not edit it. ADR-0124.\n` +
    ` */\n\n` +
    barrel.replaceAll('"', "'")
  );
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  for (const bundle of entryBundles()) {
    const text = await entryText(bundle);
    if (process.argv.includes('--write')) {
      await writeFile(bundle.entry, text);
      console.log('wrote %s', bundle.entry);
    } else {
      process.stdout.write(text);
    }
  }
}
